"""Run model-generated Python and recover its printed answer.

The PoT condition has no answer token in the model's own output -- the model
emits `print(...)`, and the value only exists once an interpreter runs.  So
execution is not an optional analysis step here; it is how the PoT label is
produced at all.

Safety: this executes text generated by a language model.  Each program runs in
a fresh subprocess, in a scratch cwd, under CPU/address-space/file-size rlimits
and a wall-clock timeout.  That contains runaway loops and memory bombs, which
is what models actually produce.  It is NOT a security sandbox -- the code can
still touch the network and the filesystem.  Run this on a machine you are
willing to have execute arbitrary Python.
"""

from __future__ import annotations

import json
import re
import resource
import subprocess
import sys
import tempfile
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Optional

from nsf.answers import extract_answer

FENCE_RE = re.compile(r"```(?:python|py)?\s*\n(.*?)(?:```|\Z)", re.DOTALL | re.IGNORECASE)


@dataclass
class ExecResult:
    ok: bool
    answer: Optional[str]
    stdout: str
    stderr: str
    status: str  # ok | timeout | error | no_code | no_answer
    returncode: Optional[int] = None

    def to_dict(self) -> dict:
        return asdict(self)


def strip_fences(completion: str) -> Optional[str]:
    """Pull runnable Python out of a completion.

    The prompt asks for bare code, but instruct models fence it anyway.  If
    fences are present we take the concatenation of every block (models
    sometimes split imports from the body).  If not, we assume the whole
    completion is code.
    """
    blocks = FENCE_RE.findall(completion)
    if blocks:
        code = "\n".join(b.rstrip() for b in blocks).strip()
        return code or None
    code = completion.strip()
    return code or None


def _limits(cpu_seconds: int, mem_bytes: int) -> None:
    """Apply rlimits best-effort.

    Each limit is applied independently and failures are swallowed: macOS
    refuses RLIMIT_AS outright, and a raising preexec_fn kills the spawn, which
    would turn every execution into a spurious `error`.  On Linux (the GPU box)
    all three apply; locally we fall back to the wall-clock timeout, which is
    what actually contains runaway loops.
    """
    for res, limit in (
        (resource.RLIMIT_CPU, (cpu_seconds, cpu_seconds)),
        (resource.RLIMIT_AS, (mem_bytes, mem_bytes)),
        (resource.RLIMIT_FSIZE, (16 * 1024 * 1024,) * 2),
    ):
        try:
            resource.setrlimit(res, limit)
        except (ValueError, OSError):
            pass


def run_code(
    code: Optional[str],
    timeout: float = 10.0,
    cpu_seconds: int = 10,
    mem_bytes: int = 2 * 1024 ** 3,
) -> ExecResult:
    if not code:
        return ExecResult(False, None, "", "", "no_code")

    with tempfile.TemporaryDirectory() as tmp:
        script = Path(tmp) / "program.py"
        script.write_text(code)
        try:
            proc = subprocess.run(
                [sys.executable, "-I", str(script)],
                capture_output=True,
                text=True,
                timeout=timeout,
                cwd=tmp,
                preexec_fn=lambda: _limits(cpu_seconds, mem_bytes),
            )
        except subprocess.TimeoutExpired:
            return ExecResult(False, None, "", "", "timeout")
        except Exception as exc:  # spawn failure, not program failure
            return ExecResult(False, None, "", f"{type(exc).__name__}: {exc}", "error")

    stdout, stderr = proc.stdout, proc.stderr
    if proc.returncode != 0:
        return ExecResult(False, None, stdout, stderr, "error", proc.returncode)

    answer = extract_answer(stdout)
    if answer is None:
        # Program ran but never printed the required line.  Fall back to the
        # last non-empty stdout line: models often print a bare value.
        lines = [ln.strip() for ln in stdout.splitlines() if ln.strip()]
        if lines:
            return ExecResult(True, lines[-1], stdout, stderr, "no_answer", 0)
        return ExecResult(False, None, stdout, stderr, "no_answer", 0)

    return ExecResult(True, answer, stdout, stderr, "ok", 0)


def run_completion(completion: str, **kw) -> ExecResult:
    return run_code(strip_fences(completion), **kw)
